//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dev_6_0874316_Jordi_Roer_INF2A
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public bool Processed { get; set; }
        public System.DateTime StartingTime { get; set; }
        public System.DateTime StoppingTime { get; set; }
        public bool OrderComplete { get; set; }
        public bool CustomerWaits { get; set; }
    }
}
